version: "3.9"
services:
  timelish-admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    image: ghcr.io/dbondarchuk/timelish-admin:latest
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/timelish?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - TZ=${TZ:-America/New_York}
      - AUTH_SECRET=${AUTH_SECRET:-n6WKAuaUVdOYMRReNYXEd/sHLF/Ddfams+FAGMe7vzk=}
      - AUTH_TRUST_HOST=${ADMIN_DOMAIN:-app.timelish.com}
      - BETTER_AUTH_URL=https://${ADMIN_DOMAIN:-app.timelish.com}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-timeli.sh}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.timelish.com}
      - APP_EXTERNAL_DOMAIN=${APP_EXTERNAL_DOMAIN:-apps.timelish.com}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - timelish-job-processor
      - timelish-notification-sender

  timelish-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: ghcr.io/dbondarchuk/timelish-web:latest
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/timelish?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - TZ=${TZ:-America/New_York}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-timeli.sh}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.timelish.com}
      - APP_EXTERNAL_DOMAIN=${APP_EXTERNAL_DOMAIN:-apps.timelish.com}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - timelish-job-processor
      - timelish-notification-sender
      - timelish-admin

  timelish-notification-sender:
    build:
      context: .
      dockerfile: apps/notification-sender/Dockerfile
    image: ghcr.io/dbondarchuk/timelish-notification-sender:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/timelish?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-timeli.sh}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.timelish.com}
      - APP_EXTERNAL_DOMAIN=${APP_EXTERNAL_DOMAIN:-apps.timelish.com}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_SECURE=${SMTP_SECURE:-true}
      - SMTP_EMAIL=${SMTP_EMAIL:-timelish@example.com}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Timeli.sh}
      - SMTP_AUTH_USER=${SMTP_AUTH_USER:-timelish@example.com}
      - SMTP_AUTH_PASS=${SMTP_AUTH_PASS:-"secure_password"}
    restart: unless-stopped

  timelish-job-processor:
    build:
      context: .
      dockerfile: apps/job-processor/Dockerfile
    image: ghcr.io/dbondarchuk/timelish-job-processor:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/timelish?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-timeli.sh}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.timelish.com}
      - APP_EXTERNAL_DOMAIN=${APP_EXTERNAL_DOMAIN:-apps.timelish.com}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped

  timelish-app-external-server:
    build:
      context: .
      dockerfile: apps/app-external-server/Dockerfile
    image: ghcr.io/dbondarchuk/timelish-app-external-server:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/timelish?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-timeli.sh}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app.timelish.com}
      - APP_EXTERNAL_DOMAIN=${APP_EXTERNAL_DOMAIN:-apps.timelish.com}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "5556:5556"

  timelish-domain-checker:
    build:
      context: .
      dockerfile: apps/domain-checker/Dockerfile
    image: ghcr.io/dbondarchuk/timelish-domain-checker:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/timelish?retryWrites=true&w=majority}
      - MONGODB_DB=${MONGODB_DB}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-timeli.sh}
    restart: unless-stopped
    ports:
      - "5555:5555"
