version: "3.9"
services:
  vivid-admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    image: ghcr.io/dbondarchuk/vivid-admin:latest
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/vivid?retryWrites=true&w=majority}
      - TZ=${TZ:-America/New_York}
      - AUTH_SECRET=${AUTH_SECRET:-n6WKAuaUVdOYMRReNYXEd/sHLF/Ddfams+FAGMe7vzk=}
      - AUTH_TRUST_HOST=${ADMIN_DOMAIN:-app-dev.vividnail.studio}
      - BETTER_AUTH_URL=https://${ADMIN_DOMAIN:-app-dev.vividnail.studio}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-vividnail.studio}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app-dev.vividnail.studio}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - "./apps/admin/public/upload:/app/public/upload"
    networks:
      - vivid-network
    depends_on:
      - vivid-job-processor
      - vivid-notification-sender

  vivid-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: ghcr.io/dbondarchuk/vivid-web:latest
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/vivid?retryWrites=true&w=majority}
      - TZ=${TZ:-America/New_York}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-vividnail.studio}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./apps/web/public/upload:/app/public/upload"
    networks:
      - vivid-network
    depends_on:
      - vivid-job-processor
      - vivid-notification-sender
      - vivid-admin

  vivid-notification-sender:
    build:
      context: .
      dockerfile: apps/notification-sender/Dockerfile
    image: ghcr.io/dbondarchuk/vivid-notification-sender:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/vivid?retryWrites=true&w=majority}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-vividnail.studio}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app-dev.vividnail.studio}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    networks:
      - vivid-network

  vivid-job-processor:
    build:
      context: .
      dockerfile: apps/job-processor/Dockerfile
    image: ghcr.io/dbondarchuk/vivid-job-processor:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/vivid?retryWrites=true&w=majority}
      - SECRET_KEY=${SECRET_KEY:-uw8iDFHFNjbIU8gPGMByTLiFfXJex7E1}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-vividnail.studio}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN:-app-dev.vividnail.studio}
      - OUTLOOK_APP_CLIENT_ID=${OUTLOOK_APP_CLIENT_ID}
      - OUTLOOK_APP_CLIENT_SECRET=${OUTLOOK_APP_CLIENT_SECRET}
      - GOOGLE_CALENDAR_APP_CLIENT_ID=${GOOGLE_CALENDAR_APP_CLIENT_ID}
      - GOOGLE_CALENDAR_APP_CLIENT_SECRET=${GOOGLE_CALENDAR_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - PAYPAL_ENVIRONMENT=${PAYPAL_ENVIRONMENT:-sandbox}
      - S3_REGION=${S3_REGION:-local}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://s3:8080}
      - S3_BUCKET=${S3_BUCKET:-assets}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    restart: unless-stopped
    networks:
      - vivid-network

  vivid-domain-checker:
    build:
      context: .
      dockerfile: apps/domain-checker/Dockerfile
    image: ghcr.io/dbondarchuk/vivid-domain-checker:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/vivid?retryWrites=true&w=majority}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-vividnail.studio}
    restart: unless-stopped
    ports:
      - "5555:5555"
    networks:
      - vivid-network

networks:
  vivid-network:
    driver: bridge
